### ISSUE TITLE
'Optimizer' not initialized

### ISSUE THREAD

**Issue by TravisTianqing** [Hsankesara/Prototypical-Networks#1]
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    main()
  File "main.py", line 42, in main
    loss, acc = train_step(protonet, trainx, trainy, 5, 60, 5)
  File "/home/serversys005/wangtianqing/mnt/prototypical/prototypicalNet.py", line 158, in train_step
    optimizer.zero_grad()
NameError: name 'optimizer' is not defined

**Comment by TravisTianqing** [comment]
It could be run when we use 'Adam' to initialize the optimizer, is this ok ?

**Comment by Hsankesara** [comment]
Hey Travis, I'm sorry I couldn't respond earlier. I was outstation for a few days. 

That is bad from my side. I'll update the patch as soon as possible.

**Comment by Hsankesara** [comment]
> It could be run when we use 'Adam' to initialize the optimizer, is this ok?

I believe Adam optimizer would work without any issues.

**Comment by Hsankesara** [comment]
Hey @TravisTianqing, I updated the code. If you again face an issue please let me know. You can also check out the [kaggle notebook](https://www.kaggle.com/hsankesara/prototypical-net/)
